apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: go-fiber
type: Opaque
stringData:
  DB_USER: "postgres"
  DB_PASSWORD: "admin123"
  DB_NAME: "categories_db" 
  SERVICE_NAME: "go-fiber-product" 
  OTEL_EXPORTER_OTLP_ENDPOINT: "otel-collector:4317"
