apiVersion: v1
kind: Service
metadata:
  name: go-fiber-http
  namespace: go-fiber
  labels:
    app: go-fiber
spec:
  selector:
    app: go-fiber
  ports:
    - name: http
      protocol: TCP
      port: 3000  
      targetPort: 3000 
  type: ClusterIP       

