apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-config
  namespace: go-fiber
data:
  jaeger.yaml: |
    apiVersion: 1
    datasources:
      - name: Jaeger
        type: jaeger
        access: proxy
        url: http://jaeger:16686
        isDefault: true
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://prometheus:9090
        isDefault: false

